name: Build and Publish Docker Container
on:
  push:
    branches:
      - main # Adjust to your main branch name or preferred branch

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and Push Docker image
        env:
          DOCKERHUB_REPO: maxon4eg/bash-exporter
        run: |
          docker build -t $DOCKERHUB_REPO:$GITHUB_SHA .
          docker push $DOCKERHUB_REPO:$GITHUB_SHA
